export const CREATE_CHARACTER = "CREATE_CHARACTER";
export const CREATING_CHARACTER = "CREATING_CHARACTER";
export const CREATING_CHARACTER_SUCCESS = "CREATING_CHARACTER_SUCCESS";
export const CREATING_CHARACTER_FAIL = "CREATING_CHARACTER_FAIL";
export const FETCHING_CHARACTERS = "FETCHING_CHARACTERS";
export const FETCHING_CHARACTERS_SUCCESS = "FETCHING_CHARACTERS_SUCCESS";
export const FETCHING_CHARACTERS_FAIL = "FETCHING_CHARACTERS_FAIL";
export const DELETING_CHARACTERS_START = "DELETING_CHARACTERS_START";
export const DELETING_CHARACTERS_SUCCESS = "DELETING_CHARACTERS_SUCCESS";
export const DELETING_CHARACTERS_FAIL = "DELETING_CHARACTERS_FAIL";
export const UPDATING_CHARACTER = "UPDATING_CHARACTER";
export const UPDATING_CHARACTER_SUCCESS = "UPDATING_CHARACTER_SUCCESS";
export const UPDATING_CHARACTER_FAIL = "UPDATING_CHARACTER_FAIL";
export const FETCHING_CHARACTER = "FETCHING_CHARACTER";
export const FETCHING_CHARACTER_SUCCESS = "FETCHING_CHARACTER_SUCCESS";
export const FETCHING_CHARACTER_FAIL = "FETCHING_CHARACTER_FAIL";
export const CLEAR_CHARACTER_EDIT = "CLEAR_CHARACTER_EDIT";


export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const CREATE_GUEST_USER_START = "CREATE_GUEST_USER_START";
export const UPDATE_NUMBER_OF_CHARACTERS = "UPDATE_NUMBER_OF_CHARACTERS";
export const CREATE_USER_START = "CREATE_USER_START";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAIL = "CREATE_USER_FAIL";
export const CREATE_GUEST_USER_SUCCESS = "CREATE_GUEST_USER_SUCCESS";
export const CREATE_GUEST_USER_FAIL = "CREATE_GUEST_USER_FAIL";
export const USER_LOGOUT_START =  "USER_LOGOUT_START";
export const USER_LOGOUT_SUCCESS =  "USER_LOGOUT_SUCCESS";
export const USER_LOGOUT_FAIL =  "USER_LOGOUT_FAIL";
export const USER_LOGIN_START =  "USER_LOGIN_START";
export const USER_LOGIN_SUCCESS =  "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL =  "USER_LOGIN_FAIL";
export const FETCH_USER_START =  "FETCH_USER_START";
export const FETCH_USER_SUCCESS =  "FETCH_USER_SUCCESS";
export const FETCH_USER_FAIL =  "FETCH_USER_FAIL";



