const CharacterModel = () => {
  return {
    user: String,
    basics: {
      name: String,
      player: String,
      LVL: String,
      XP: String,
      homeland: String,
      type: String,
      alignment: String,
      deity: String,
      abilityBoost: String,
    },
    appearance: {
      age: String,
      eyes: String,
      hair: String,
      weight: String,
      height: String,
      gender: String,
    },
    mainStats: {
      STR: String,
      DEX: String,
      CON: String,
      INT: String,
      WIS: String,
      CHA: String,
      AC: String,
      TOUCHAC: String,
      HP: String,
    },
    modifiers: {
      CHA: String,
      CON: String,
      DEX: String,
      INT: String,
      WIS: String,
      STR: String,
      FORT: String,
      REFLEX: String,
      TOUCHAC: String,
      AC: String,
      PER: String,
    },
    items: {
      worn: String,
      ready: String,
      stowed: String,
      coins: {
        platinum: Number,
        gold: Number,
        silver: Number,
        copper: Number,
      },
      bulk: String,
    },
    ancestryProps: {
      ancestry: String,
      size: String,
      speed: Number,
      languages: String,
      ancestryTraits: Array,
      attributes: Object
    },
    backgroundProps: {
      background: String,
      selectBoost: Array,
      freeAbilityBoost: Number,
      skillFeat: String,
      loreSkill: String,
    },
    classProps: {
      class: String,
      keyAbility: Array,
      proficiencies: Object,
      savingThrows: Object,
      skills: Object,
      weapons: Object,
      armor: Object,
      signatureSkills: Array,
      classFeatures: Array,
      items: Object,
    },
    characterTraits: Object,
    characterNotes: String,
    skillsModifiers: Object,
    skillFeats: String,
    spells: Object,
    actions: {
      string: String,
      melee: Array,
      ranged: Array,
    },
    feats: Object,
  };
};
